version: '3.9'

services:
  backend:
    working_dir: /app
    image: mcr.microsoft.com/dotnet/sdk:5.0
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80  
    volumes:
      - .:/app
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    command: dotnet restore && dotnet dev-certs https -t
    entrypoint: dotnet run
    ports:
      - "5000:5000"
